CREATE TABLE dbo.CARDIO_TRAIN (
    ID          INT          NOT NULL CONSTRAINT PK_CARDIO_TRAIN PRIMARY KEY,
    AGE         INT          NOT NULL CONSTRAINT CK_AGE_POSITIVE CHECK (AGE > 0),
    GENDER      TINYINT      NOT NULL CONSTRAINT CK_GENDER CHECK (GENDER IN (1, 2)),
    HEIGHT      SMALLINT     NOT NULL,
    WEIGHT      DECIMAL(6,2) NOT NULL,
    AP_HI       SMALLINT     NOT NULL,
    AP_LO       SMALLINT     NOT NULL,
    CHOLESTEROL TINYINT      NOT NULL CONSTRAINT CK_CHOLESTEROL CHECK (CHOLESTEROL IN (1, 2, 3)),
    GLUC        TINYINT      NOT NULL CONSTRAINT CK_GLUC CHECK (GLUC IN (1, 2, 3)),
    SMOKE       TINYINT      NOT NULL CONSTRAINT CK_SMOKE CHECK (SMOKE IN (0, 1)),
    ALCO        TINYINT      NOT NULL CONSTRAINT CK_ALCO CHECK (ALCO IN (0, 1)),
    ACTIVE      TINYINT      NOT NULL CONSTRAINT CK_ACTIVE CHECK (ACTIVE IN (0, 1)),
    CARDIO      TINYINT      NOT NULL CONSTRAINT CK_CARDIO CHECK (CARDIO IN (0, 1))
);
