-- Optional manual load in SSMS. Notebook 01 performs the same steps automatically.
-- Edit the file path so it points to data\cardio_train_raw.csv on the SQL Server machine.

IF DB_ID(N'CardioDB') IS NULL CREATE DATABASE CardioDB;
GO
USE CardioDB;
GO

IF OBJECT_ID(N'dbo.CARDIO_TRAIN', N'U') IS NULL
BEGIN
    CREATE TABLE dbo.CARDIO_TRAIN (
        ID INT NOT NULL CONSTRAINT PK_CARDIO_TRAIN PRIMARY KEY,
        AGE INT NOT NULL CONSTRAINT CK_AGE_POSITIVE CHECK (AGE > 0),
        GENDER TINYINT NOT NULL CONSTRAINT CK_GENDER CHECK (GENDER IN (1, 2)),
        HEIGHT SMALLINT NOT NULL,
        WEIGHT DECIMAL(5,1) NOT NULL,
        AP_HI SMALLINT NOT NULL,
        AP_LO SMALLINT NOT NULL,
        CHOLESTEROL TINYINT NOT NULL CONSTRAINT CK_CHOLESTEROL CHECK (CHOLESTEROL IN (1, 2, 3)),
        GLUC TINYINT NOT NULL CONSTRAINT CK_GLUC CHECK (GLUC IN (1, 2, 3)),
        SMOKE TINYINT NOT NULL CONSTRAINT CK_SMOKE CHECK (SMOKE IN (0, 1)),
        ALCO TINYINT NOT NULL CONSTRAINT CK_ALCO CHECK (ALCO IN (0, 1)),
        ACTIVE TINYINT NOT NULL CONSTRAINT CK_ACTIVE CHECK (ACTIVE IN (0, 1)),
        CARDIO TINYINT NOT NULL CONSTRAINT CK_CARDIO CHECK (CARDIO IN (0, 1))
    );

    BULK INSERT dbo.CARDIO_TRAIN
    FROM 'C:\ADY201m\data\cardio_train_raw.csv'
    WITH (FIRSTROW = 2, FIELDTERMINATOR = ';', ROWTERMINATOR = '0x0a', TABLOCK);
END
GO

SELECT COUNT(*) AS TOTAL_ROWS, SUM(CAST(CARDIO AS INT)) AS DISEASE_CASES FROM dbo.CARDIO_TRAIN;
DBCC CHECKTABLE('dbo.CARDIO_TRAIN');
